name: Auto update

on:
  schedule:
    - cron: '37 19 * * *'
  workflow_dispatch:


jobs:
  update:
    runs-on: ubuntu-latest
    container:
      image: archlinux

    steps:

      - name: Get time
        id: time
        run: echo "::set-output name=time::$(date +%F-%T)"

      - name: Set up cache
        uses: actions/cache@master
        with:
          path: /var/cache/pacman/pkg
          key: pacman-cache-x86_64-${{ steps.time.outputs.time }}
          restore-keys: pacman-cache-x86_64-

      - name: Install packages
        run: |
          pacman -Syu --noconfirm
          pacman -S --needed --noconfirm git python-setuptools pacman-contrib openssh

      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: JinnLynn/genpac
          path: genpac

      - uses: actions/checkout@v2
        with:
          repository: gfwlist/gfwlist
          path: gfwlist

      - run: |
          cd genpac
          sed 's/from collections import Callable/from collections.abc import Callable/g' -i $(grep 'from collections import Callable' . -rIl)
          python setup.py install


      - name: Update
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          set -x

          mkdir -p ~/.ssh/
          echo "$ACCESS_TOKEN" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email ${{ secrets.GIT_COMMIT_EMAIL }}
          git config --global user.name ${{ secrets.GIT_COMMIT_NAME }}

          genpac --pac-proxy "SOCKS5 127.0.0.1:7890" --gfwlist-url - --gfwlist-local gfwlist/gfwlist.txt -o gfwlist.pac
          sed '1,7d' -i gfwlist.pac
          git config --global --add safe.directory /__w/gfwlist2pac/gfwlist2pac

          git add gfwlist.pac
          git commit -m "[$(LANG=C date)] auto update" || exit
          [ -n "${{ secrets.READ_ONLY }}" ] && git show && exit
          git push origin master

