name: Auto update

on:
  schedule:
    - cron: '37 19 * * *'
  workflow_dispatch:


jobs:
  update:
    runs-on: ubuntu-latest
    container:
      image: archlinux

    steps:

      - name: Get time
        id: time
        run: echo "::set-output name=time::$(date +%F-%T)"

      - name: Set up cache
        uses: actions/cache@master
        with:
          path: /var/cache/pacman/pkg
          key: pacman-cache-x86_64-${{ steps.time.outputs.time }}
          restore-keys: pacman-cache-x86_64-

      - name: Install packages
        run: |
          pacman -Syu --noconfirm
          pacman -S --needed --noconfirm git python-setuptools pacman-contrib openssh

      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: JinnLynn/genpac
          path: genpac

      - uses: actions/checkout@v2
        with:
          repository: gfwlist/gfwlist
          path: gfwlist

      - run: |
          cd genpac
          sed 's/from collections import Callable/from collections.abc import Callable/g' -i $(grep 'from collections import Callable' . -rIl)
          python setup.py install


      - name: Update
        run: |
          set -x

          genpac --pac-proxy "SOCKS5 127.0.0.1:7890" --gfwlist-url - --gfwlist-local gfwlist/gfwlist.txt -o gfwlist.pac
          sed '1,7d' -i gfwlist.pac
          git config --global --add safe.directory /__w/gfwlist2pac/gfwlist2pac

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: .
          file_pattern: "*.pac"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
